### ISSUE TITLE
Jogo => Forca

### ISSUE THREAD

**Issue by LaraFer10** [LaraFer10/JogosLPA#2]
Desenvolver um jogo da Forca em Java considerando a passagem de parâmetro por valor, delegação de responsabilidade para os métodos e implementação correta do jogo. 
1) Como dica da palavra oculta, utilize o número de letras, indicado através de um traçado.

2) A cada letra errada é desenhado uma parte do corpo do enforcado e a cada letra certa o traçado é substituído pela letra.

3) Se o jogador conseguir adivinhar a palavra antes de finalizar o desenho do enforcado ele ganha o jogo.

Utilize métodos para:

a. Construir a forca e o enforcado
b. Definir a palavra oculta
c. Efetuar a jogada
d. Validar a jogada
e. Efetuar a estratégia
f. Identificar o vencedor | perdedor

**Comment by TatianeXimenes** [comment]
Atividade feita no pull request #7
